let reportHtml = "";
const reportById = id => document.getElementById(id);
const reportSession = id => data.sessions.find(item => item.id === id);
const reportEsc = value => String(value ?? "").replace(/[&<>"']/g, character => ({"&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;"}[character]));
const reportKpi = (label, value) => `<b>${label}<span>${value}</span></b>`;
const reportSummary = list => ({total:list.length, present:list.filter(item => item.status === "present").length, absent:list.filter(item => item.status === "absent").length});
const reportValue = value => String(value || "");
const reportSessionMatches = session => {
  const value = id => reportById(id)?.value || "";
  return (!value("reportCourse") || reportValue(session.courseName).toLowerCase().includes(value("reportCourse").toLowerCase())) &&
    (!value("reportClass") || reportValue(session.className).toLowerCase().includes(value("reportClass").toLowerCase())) &&
    (!value("reportSection") || reportValue(session.section).toLowerCase().includes(value("reportSection").toLowerCase())) &&
    (!value("reportTeacher") || reportValue(session.teacherName).toLowerCase().includes(value("reportTeacher").toLowerCase())) &&
    (!value("reportSubject") || reportValue(session.subjectName).toLowerCase().includes(value("reportSubject").toLowerCase()));
};
const reportRecords = () => data.attendance.filter(record => {
  const session = reportSession(record.sessionId);
  if (!session) return false;
  const studentId = reportById("reportStudent").value;
  const from = reportById("reportFrom").value;
  const to = reportById("reportTo").value;
  return (studentId === "all" || record.studentId === studentId) &&
    reportSessionMatches(session) &&
    (!from || record.date >= from) && (!to || record.date <= to);
});
const reportHeader = (title, session) => `<header class="report-header"><p class="report-institution">${reportEsc(reportById("reportInstitution").value || "Attendance Management System")}</p><h1>${title}</h1><p><strong>Class:</strong> ${reportEsc(session?.className || reportById("reportClass").value || "All classes")} &nbsp; <strong>Department:</strong> ${reportEsc(session?.department || reportById("reportDepartment").value)} &nbsp; <strong>Section:</strong> ${reportEsc(session?.section || reportById("reportSection").value || "All sections")}</p><p><strong>Subject:</strong> ${reportEsc(session?.subjectName || reportById("reportSubject").value || "All subjects")} &nbsp; <strong>Teacher:</strong> ${reportEsc(session?.teacherName || reportById("reportTeacher").value || "-")}</p><p><strong>Date:</strong> ${reportEsc(session?.date || "All dates")} &nbsp; <strong>Time:</strong> ${reportEsc(session?.startTime || "-")} - ${reportEsc(session?.endTime || "-")}</p></header>`;
const reportFooter = () => `<footer class="report-footer">Generated on: ${new Date().toLocaleString()}<br><br>Teacher Signature: ____________________<br><br>Authorized Signature: ____________________</footer>`;
function reportTableRows(list, detailed) { return list.map(record => { const person = student(record.studentId); const session = reportSession(record.sessionId); return `<tr><td>${person?.rollNo || ""}</td><td>${reportEsc(person?.studentId || person?.id || record.studentId || "")}</td><td>${reportEsc(person?.name || "")}</td>${detailed ? `<td>${record.date}</td><td>${reportEsc(session?.subjectName || record.subjectName)}</td><td>${reportEsc(session?.teacherName || record.teacherName)}</td><td>${session?.startTime || session?.scheduledTime || ""}</td>` : ""}<td class="${record.status === "present" ? "good" : "bad"}">${record.status}</td><td>${record.markedTime || session?.markingTime || ""}</td></tr>`; }).join(""); }
function makeReport() {
  const type = reportById("reportType").value;
  const allRecords = reportRecords();
  const firstSession = [...data.attendanceSessions].reverse().find(reportSessionMatches);
  const sessionRecords = firstSession ? allRecords.filter(record => record.sessionId === firstSession.id) : [];
  const list = ["class", "daily", "present"].includes(type) ? sessionRecords : allRecords;
  const summary = reportSummary(list);
  if (type === "student" && reportById("reportStudent").value === "all") return toast("Select one student for an individual report");
  if (type === "student") {
    const person = student(reportById("reportStudent").value);
    reportHtml = `${reportHeader("Student Attendance Report", firstSession)}<h2>Student: ${reportEsc(person?.name)}</h2><p>Roll No: ${person?.rollNo || ""}</p><div class="report-kpis">${reportKpi("Total classes", summary.total)}${reportKpi("Present", summary.present)}${reportKpi("Absent", summary.absent)}${reportKpi("Attendance", `${pct(summary.present, summary.total)}%`)}</div><div class="tablewrap"><table><thead><tr><th>Roll</th><th>Student</th><th>Date</th><th>Subject</th><th>Teacher</th><th>Class time</th><th>Status</th><th>Marked time</th></tr></thead><tbody>${reportTableRows(list, true)}</tbody></table></div><p>Target Attendance: ${data.settings.target}% · Status: ${pct(summary.present, summary.total) >= data.settings.target ? "Above Target" : "Below Target"}</p>${reportFooter()}`;
  } else if (type === "daily" || type === "present") {
    const visible = type === "present" ? list.filter(item => item.status === "present") : list;
    reportHtml = `${reportHeader(type === "present" ? "Present Students" : "Daily Attendance Sheet", firstSession)}<div class="report-kpis">${reportKpi("Total students", firstSession?.totalStudentsAtTime || list.length)}${reportKpi("Present", summary.present)}${reportKpi("Absent", summary.absent)}${reportKpi("Attendance", `${pct(summary.present, summary.total)}%`)}</div><div class="tablewrap"><table><thead><tr><th>Roll</th><th>Student ID</th><th>Student Name</th><th>Status</th><th>Marked Time</th></tr></thead><tbody>${reportTableRows(visible, false)}</tbody></table></div>${reportFooter()}`;
  } else if (type === "analysis") {
    const byStudent = {};
    list.forEach(item => (byStudent[item.studentId] ||= []).push(item));
    const rows = Object.entries(byStudent).map(([id, recordsForStudent]) => { const itemSummary = reportSummary(recordsForStudent); return `<tr><td>${student(id)?.rollNo || ""}</td><td>${reportEsc(student(id)?.name)}</td><td>${itemSummary.total}</td><td>${itemSummary.present}</td><td>${itemSummary.absent}</td><td>${pct(itemSummary.present, itemSummary.total)}%</td></tr>`; }).join("");
    reportHtml = `${reportHeader("Attendance Analysis Report")}<div class="report-kpis">${reportKpi("Total students", data.students.length)}${reportKpi("Total classes", data.sessions.length)}${reportKpi("Attendance records", list.length)}${reportKpi("Average attendance", `${pct(summary.present, summary.total)}%`)}</div><h2>Student-wise Analysis</h2><div class="tablewrap"><table><thead><tr><th>Roll</th><th>Student</th><th>Classes</th><th>Present</th><th>Absent</th><th>Attendance</th></tr></thead><tbody>${rows}</tbody></table></div>${reportFooter()}`;
  } else {
    const grouped = {};
    list.forEach(item => (grouped[item.studentId] ||= []).push(item));
    const subjects = [...new Set(list.map(item => reportSession(item.sessionId)?.subjectName || item.subjectName))];
    const rows = Object.entries(grouped).map(([id, recordsForStudent]) => { const itemSummary = reportSummary(recordsForStudent); const person = student(id); const cells = subjects.map(name => recordsForStudent.some(item => (reportSession(item.sessionId)?.subjectName || item.subjectName) === name && item.status === "present") ? "P" : "A").join("</td><td>"); return `<tr><td>${person?.rollNo || ""}</td><td>${reportEsc(person?.studentId || person?.id || id)}</td><td>${reportEsc(person?.name)}</td><td>${cells}</td><td>${pct(itemSummary.present, itemSummary.total)}%</td></tr>`; }).join("");
    reportHtml = `${reportHeader("Complete Class Attendance", firstSession)}<div class="report-kpis">${reportKpi("Students", firstSession?.totalStudentsAtTime || Object.keys(grouped).length)}${reportKpi("Present records", summary.present)}${reportKpi("Absent records", summary.absent)}${reportKpi("Attendance", `${pct(summary.present, summary.total)}%`)}</div><div class="tablewrap report-wide"><table><thead><tr><th>Roll</th><th>Student ID</th><th>Student</th>${subjects.map(item => `<th>${reportEsc(item)}</th>`).join("")}<th>Overall</th></tr></thead><tbody>${rows}</tbody></table></div>${reportFooter()}`;
  }
  reportById("reportPreview").innerHTML = reportHtml;
  reportById("reportStatus").textContent = `${list.length} records`;
}
function reportText() { const node = document.createElement("div"); node.innerHTML = reportHtml; return node.innerText.replace(/\n{3,}/g, "\n\n").trim(); }
async function shareGeneratedReport() { makeReport(); const text = reportText(); if (navigator.share) await navigator.share({title:"Attendance Report",text}); else { await navigator.clipboard.writeText(text); toast("Share is not supported; report copied successfully."); } }
function printGeneratedReport() { makeReport(); const printArea = reportById("printArea"); printArea.innerHTML = ""; printArea.innerHTML = reportHtml; document.body.classList.add("print-mode"); window.print(); setTimeout(() => { document.body.classList.remove("print-mode"); printArea.innerHTML = ""; }, 500); }
function exportGeneratedCsv() { const list = reportRecords(); const rows = list.map(item => { const person = student(item.studentId), session = reportSession(item.sessionId); return [person?.id, person?.rollNo, person?.name, session?.courseName, session?.subjectName, session?.className, session?.section, session?.teacherName, item.date, session?.scheduledTime, item.markedTime || session?.markingTime, item.status]; }); const csv = [["Student ID","Roll No","Student Name","Course","Subject","Class","Section","Teacher","Date","Scheduled Time","Marked Time","Status"], ...rows].map(row => row.map(value => `"${String(value ?? "").replace(/"/g, '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], {type:"text/csv"})); link.download = "attendance-report.csv"; link.click(); }
function populateReportStudents() { reportById("reportStudent").innerHTML = `<option value="all">All Students</option>${data.students.map(item => `<option value="${item.id}">${item.rollNo}. ${reportEsc(item.name)}</option>`).join("")}`; }
document.addEventListener("DOMContentLoaded", () => { populateReportStudents(); reportById("generateReport").onclick = makeReport; reportById("printReport").onclick = printGeneratedReport; reportById("pdfReport").onclick = printGeneratedReport; reportById("shareReport").onclick = shareGeneratedReport; reportById("copyReport").onclick = async () => { makeReport(); await navigator.clipboard.writeText(reportText()); toast("Report copied successfully"); }; reportById("sharePresent").onclick = async () => { reportById("reportType").value = "present"; await shareGeneratedReport(); }; reportById("exportReport").onclick = exportGeneratedCsv; document.querySelector('[data-page="reports"]')?.addEventListener("click", populateReportStudents); });
const reportStyle = document.createElement("style"); reportStyle.textContent = `#printArea{display:none}.report-filters{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.report-filters label{display:grid;gap:5px;color:#8993a7;font-size:12px}.report-actions{display:flex;gap:10px;flex-wrap:wrap}.report-header{border-bottom:2px solid #222936;padding-bottom:14px;margin-bottom:18px}.report-header h1{margin:5px 0}.report-header p{line-height:1.6;margin:6px 0}.report-institution{font-size:20px;font-weight:700}.report-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:15px 0}.report-kpis b{background:#171b25;padding:12px;color:#8993a7;border-radius:8px}.report-kpis span{display:block;color:#fff;font-size:20px;margin-top:4px}.report-footer{margin-top:25px;border-top:1px solid #bbb;padding-top:15px}.print-mode .app,.print-mode #toast{display:none}.print-mode #printArea{display:block;background:#fff;color:#111;padding:12mm;font:12px Arial;min-height:100vh}.print-mode #printArea .report-kpis b{background:#f2f2f2;color:#333;border:1px solid #ccc}.print-mode #printArea .report-kpis span,.print-mode #printArea td,.print-mode #printArea th{color:#111}.print-mode #printArea table{min-width:0;color:#111}.print-mode #printArea th,.print-mode #printArea td{border-bottom:1px solid #bbb;padding:6px 5px}.print-mode #printArea th{background:#f2f2f2}.print-mode #printArea .report-header{border-color:#111}@media(max-width:800px){.report-filters{grid-template-columns:1fr 1fr}.report-kpis{grid-template-columns:repeat(2,1fr)}}@media print{body.print-mode{background:#fff}.print-mode #printArea{display:block}@page{size:A4 portrait;margin:12mm}.report-wide{page-break-inside:auto}.report-wide thead{display:table-header-group}.report-wide tr{page-break-inside:avoid}}`; document.head.appendChild(reportStyle);
data.sessions.forEach(session => { if (!session.studentCountSnapshot) session.studentCountSnapshot = records(session.id).length; }); save();
fetch(`https://date.nager.at/api/v3/PublicHolidays/${data.settings.year}/IN`).then(response => response.ok ? response.json() : Promise.reject()).then(holidays => { data.holidays = {}; holidays.forEach(item => data.holidays[item.date] = item.localName || item.name); save(); if (typeof renderCalendar === "function") renderCalendar(); }).catch(() => toast("Could not load Nager.Date holidays"));